language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script: "mvn clean install -Pit-js -Pci-build"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - olamy@apache.org
