begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|lucene
package|;
end_package

begin_comment
comment|/*  * Copyright 2005-2006 The Apache Software Foundation.  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|RepositoryArtifactIndex
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|RepositoryArtifactIndexFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|project
operator|.
name|MavenProjectBuilder
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_comment
comment|/**  * Factory for Lucene artifact index instances.  *  * @author<a href="mailto:brett@apache.org">Brett Porter</a>  * @plexus.component role="org.apache.maven.archiva.indexer.RepositoryArtifactIndexFactory" role-hint="lucene"  */
end_comment

begin_class
specifier|public
class|class
name|LuceneRepositoryArtifactIndexFactory
implements|implements
name|RepositoryArtifactIndexFactory
block|{
comment|/**      * @plexus.requirement      * @todo remove when MNG-142 is fixed      */
specifier|private
name|MavenProjectBuilder
name|projectBuilder
decl_stmt|;
specifier|public
name|RepositoryArtifactIndex
name|createStandardIndex
parameter_list|(
name|File
name|indexPath
parameter_list|)
block|{
return|return
operator|new
name|LuceneRepositoryArtifactIndex
argument_list|(
name|indexPath
argument_list|,
operator|new
name|LuceneStandardIndexRecordConverter
argument_list|()
argument_list|,
name|projectBuilder
argument_list|)
return|;
block|}
specifier|public
name|RepositoryArtifactIndex
name|createMinimalIndex
parameter_list|(
name|File
name|indexPath
parameter_list|)
block|{
return|return
operator|new
name|LuceneRepositoryArtifactIndex
argument_list|(
name|indexPath
argument_list|,
operator|new
name|LuceneMinimalIndexRecordConverter
argument_list|()
argument_list|,
name|projectBuilder
argument_list|)
return|;
block|}
block|}
end_class

end_unit

