begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|web
operator|.
name|action
operator|.
name|admin
operator|.
name|repositories
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|lang
operator|.
name|StringUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|common
operator|.
name|utils
operator|.
name|PathUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|configuration
operator|.
name|RepositoryConfiguration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|model
operator|.
name|RepositoryContentStatistics
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|model
operator|.
name|RepositoryURL
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_comment
comment|/**  * AdminRepositoryConfiguration   *  * @author<a href="mailto:joakime@apache.org">Joakim Erdfelt</a>  * @version $Id$  */
end_comment

begin_class
specifier|public
class|class
name|AdminRepositoryConfiguration
extends|extends
name|RepositoryConfiguration
block|{
specifier|private
name|RepositoryContentStatistics
name|stats
decl_stmt|;
specifier|public
name|AdminRepositoryConfiguration
parameter_list|()
block|{
name|super
argument_list|()
expr_stmt|;
block|}
comment|/**      * Copy Constructor.      */
specifier|public
name|AdminRepositoryConfiguration
parameter_list|(
name|RepositoryConfiguration
name|repoconfig
parameter_list|)
block|{
name|this
operator|.
name|setId
argument_list|(
name|repoconfig
operator|.
name|getId
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setName
argument_list|(
name|repoconfig
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setUrl
argument_list|(
name|repoconfig
operator|.
name|getUrl
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setLayout
argument_list|(
name|repoconfig
operator|.
name|getLayout
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setIndexed
argument_list|(
name|repoconfig
operator|.
name|isIndexed
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setReleases
argument_list|(
name|repoconfig
operator|.
name|isReleases
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setSnapshots
argument_list|(
name|repoconfig
operator|.
name|isSnapshots
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setIndexDir
argument_list|(
name|repoconfig
operator|.
name|getIndexDir
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|setRefreshCronExpression
argument_list|(
name|repoconfig
operator|.
name|getRefreshCronExpression
argument_list|()
argument_list|)
expr_stmt|;
if|if
condition|(
name|repoconfig
operator|.
name|isManaged
argument_list|()
condition|)
block|{
name|RepositoryURL
name|url
init|=
operator|new
name|RepositoryURL
argument_list|(
name|repoconfig
operator|.
name|getUrl
argument_list|()
argument_list|)
decl_stmt|;
name|this
operator|.
name|setDirectory
argument_list|(
name|url
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|boolean
name|isDirectoryExists
parameter_list|()
block|{
if|if
condition|(
name|StringUtils
operator|.
name|isBlank
argument_list|(
name|getDirectory
argument_list|()
argument_list|)
condition|)
block|{
return|return
literal|false
return|;
block|}
name|File
name|dir
init|=
operator|new
name|File
argument_list|(
name|getDirectory
argument_list|()
argument_list|)
decl_stmt|;
return|return
operator|(
name|dir
operator|.
name|exists
argument_list|()
operator|&&
name|dir
operator|.
name|isDirectory
argument_list|()
operator|)
return|;
block|}
specifier|public
name|String
name|getDirectory
parameter_list|()
block|{
if|if
condition|(
name|this
operator|.
name|isManaged
argument_list|()
condition|)
block|{
if|if
condition|(
name|StringUtils
operator|.
name|isBlank
argument_list|(
name|this
operator|.
name|getUrl
argument_list|()
argument_list|)
condition|)
block|{
return|return
literal|null
return|;
block|}
name|RepositoryURL
name|url
init|=
operator|new
name|RepositoryURL
argument_list|(
name|this
operator|.
name|getUrl
argument_list|()
argument_list|)
decl_stmt|;
return|return
name|url
operator|.
name|getPath
argument_list|()
return|;
block|}
return|return
literal|null
return|;
block|}
specifier|public
name|void
name|setDirectory
parameter_list|(
name|String
name|directory
parameter_list|)
block|{
name|this
operator|.
name|setUrl
argument_list|(
name|PathUtil
operator|.
name|toUrl
argument_list|(
name|directory
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|RepositoryContentStatistics
name|getStats
parameter_list|()
block|{
return|return
name|stats
return|;
block|}
specifier|public
name|void
name|setStats
parameter_list|(
name|RepositoryContentStatistics
name|stats
parameter_list|)
block|{
name|this
operator|.
name|stats
operator|=
name|stats
expr_stmt|;
block|}
block|}
end_class

end_unit

