begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|repository
operator|.
name|indexing
operator|.
name|record
package|;
end_package

begin_comment
comment|/*  * Copyright 2005-2006 The Apache Software Foundation.  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|artifact
operator|.
name|Artifact
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|repository
operator|.
name|digest
operator|.
name|Digester
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_comment
comment|/**  * An index record type for the standard index.  *  * @author Edwin Punzalan  * @author Brett Porter  * @plexus.component role="org.apache.maven.repository.indexing.record.RepositoryIndexRecordFactory" role-hint="standard"  */
end_comment

begin_class
specifier|public
class|class
name|StandardArtifactIndexRecordFactory
extends|extends
name|AbstractArtifactIndexRecordFactory
block|{
comment|/**      * A list of artifact types to treat as a zip archive.      *      * @todo this should be smarter (perhaps use plexus archiver to look for an unarchiver, and make the ones for zip configurable since sar, par, etc can be added at random.      */
specifier|private
specifier|static
specifier|final
name|Set
name|ARCHIVE_TYPES
init|=
operator|new
name|HashSet
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
operator|new
name|String
index|[]
block|{
literal|"jar"
block|,
literal|"zip"
block|,
literal|"ejb"
block|,
literal|"par"
block|,
literal|"sar"
block|,
literal|"war"
block|,
literal|"ear"
block|}
argument_list|)
argument_list|)
decl_stmt|;
specifier|public
name|RepositoryIndexRecord
name|createRecord
parameter_list|(
name|Artifact
name|artifact
parameter_list|)
block|{
name|StandardArtifactIndexRecord
name|record
init|=
literal|null
decl_stmt|;
name|File
name|file
init|=
name|artifact
operator|.
name|getFile
argument_list|()
decl_stmt|;
if|if
condition|(
name|file
operator|!=
literal|null
operator|&&
name|file
operator|.
name|exists
argument_list|()
condition|)
block|{
name|String
name|md5
init|=
name|readChecksum
argument_list|(
name|file
argument_list|,
name|Digester
operator|.
name|MD5
argument_list|)
decl_stmt|;
name|String
name|sha1
init|=
name|readChecksum
argument_list|(
name|file
argument_list|,
name|Digester
operator|.
name|SHA1
argument_list|)
decl_stmt|;
name|List
name|files
init|=
literal|null
decl_stmt|;
try|try
block|{
if|if
condition|(
name|ARCHIVE_TYPES
operator|.
name|contains
argument_list|(
name|artifact
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
block|{
name|files
operator|=
name|readFilesInArchive
argument_list|(
name|file
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|files
operator|=
name|Collections
operator|.
name|EMPTY_LIST
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|getLogger
argument_list|()
operator|.
name|error
argument_list|(
literal|"Error reading artifact file, omitting from index: "
operator|+
name|e
operator|.
name|getMessage
argument_list|()
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|files
operator|!=
literal|null
condition|)
block|{
name|record
operator|=
operator|new
name|StandardArtifactIndexRecord
argument_list|()
expr_stmt|;
name|record
operator|.
name|setGroupId
argument_list|(
name|artifact
operator|.
name|getGroupId
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setArtifactId
argument_list|(
name|artifact
operator|.
name|getArtifactId
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setVersion
argument_list|(
name|artifact
operator|.
name|getVersion
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setClassifier
argument_list|(
name|artifact
operator|.
name|getClassifier
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setType
argument_list|(
name|artifact
operator|.
name|getType
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setMd5Checksum
argument_list|(
name|md5
argument_list|)
expr_stmt|;
name|record
operator|.
name|setSha1Checksum
argument_list|(
name|sha1
argument_list|)
expr_stmt|;
name|record
operator|.
name|setFilename
argument_list|(
name|file
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setLastModified
argument_list|(
name|file
operator|.
name|lastModified
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setSize
argument_list|(
name|file
operator|.
name|length
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setRepository
argument_list|(
name|artifact
operator|.
name|getRepository
argument_list|()
operator|.
name|getId
argument_list|()
argument_list|)
expr_stmt|;
comment|/* TODO! these come from the POM and metadata, so probably part of an update record method instead // remember to test parent& inheritence                 record.setPluginPrefix( pluginPrefix );                 record.setPackaging( packaging );                 record.setProjectName( name );                 record.setProjectDescription( description );                 record.setInceptionYear( year );                 */
comment|/* TODO: fields for later                 indexPlugins( doc, FLD_PLUGINS_BUILD, pom.getBuild().getPlugins().iterator() );                 indexReportPlugins( doc, FLD_PLUGINS_REPORT, pom.getReporting().getPlugins().iterator() );                 record.setDependencies( dependencies );                 record.setLicenses( licenses ); */
name|populateArchiveEntries
argument_list|(
name|files
argument_list|,
name|record
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|record
return|;
block|}
specifier|private
name|void
name|populateArchiveEntries
parameter_list|(
name|List
name|files
parameter_list|,
name|StandardArtifactIndexRecord
name|record
parameter_list|)
block|{
name|StringBuffer
name|classes
init|=
operator|new
name|StringBuffer
argument_list|()
decl_stmt|;
name|StringBuffer
name|packages
init|=
operator|new
name|StringBuffer
argument_list|()
decl_stmt|;
name|StringBuffer
name|fileBuffer
init|=
operator|new
name|StringBuffer
argument_list|()
decl_stmt|;
for|for
control|(
name|Iterator
name|i
init|=
name|files
operator|.
name|iterator
argument_list|()
init|;
name|i
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|String
name|name
init|=
operator|(
name|String
operator|)
name|i
operator|.
name|next
argument_list|()
decl_stmt|;
comment|// ignore directories
if|if
condition|(
operator|!
name|name
operator|.
name|endsWith
argument_list|(
literal|"/"
argument_list|)
condition|)
block|{
name|fileBuffer
operator|.
name|append
argument_list|(
name|name
argument_list|)
operator|.
name|append
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
if|if
condition|(
name|isClass
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|int
name|idx
init|=
name|name
operator|.
name|lastIndexOf
argument_list|(
literal|'/'
argument_list|)
decl_stmt|;
name|String
name|classname
init|=
name|name
operator|.
name|substring
argument_list|(
name|idx
operator|+
literal|1
argument_list|,
name|name
operator|.
name|length
argument_list|()
operator|-
literal|6
argument_list|)
decl_stmt|;
name|classes
operator|.
name|append
argument_list|(
name|classname
argument_list|)
operator|.
name|append
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
if|if
condition|(
name|idx
operator|>
literal|0
condition|)
block|{
name|String
name|packageName
init|=
name|name
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|idx
argument_list|)
operator|.
name|replace
argument_list|(
literal|'/'
argument_list|,
literal|'.'
argument_list|)
decl_stmt|;
if|if
condition|(
name|packages
operator|.
name|indexOf
argument_list|(
name|packageName
argument_list|)
operator|<
literal|0
condition|)
block|{
name|packages
operator|.
name|append
argument_list|(
name|packageName
argument_list|)
operator|.
name|append
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
block|}
name|record
operator|.
name|setClasses
argument_list|(
name|classes
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setPackages
argument_list|(
name|packages
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|record
operator|.
name|setFiles
argument_list|(
name|fileBuffer
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

