begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|metadata
operator|.
name|repository
operator|.
name|cassandra
operator|.
name|model
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_comment
comment|/**  * Cassandra column names  *   * @author carlos@apache.org  */
end_comment

begin_enum
specifier|public
enum|enum
name|ColumnNames
block|{
name|FACET_ID
argument_list|(
literal|"facetId"
argument_list|)
block|,
name|REPOSITORY_NAME
argument_list|(
literal|"repositoryName"
argument_list|)
block|,
name|NAME
argument_list|(
literal|"name"
argument_list|)
block|,
name|NAMESPACE_ID
argument_list|(
literal|"namespaceId"
argument_list|)
block|,
name|PROJECT_ID
argument_list|(
literal|"projectId"
argument_list|)
block|,
name|PROJECT_VERSION
argument_list|(
literal|"projectVersion"
argument_list|)
block|,
name|KEY
argument_list|(
literal|"facetKey"
argument_list|)
block|,
name|VALUE
argument_list|(
literal|"value"
argument_list|)
block|,
name|ID
argument_list|(
literal|"id"
argument_list|)
block|,
name|SIZE
argument_list|(
literal|"size"
argument_list|)
block|,
name|MD5
argument_list|(
literal|"md5"
argument_list|)
block|,
name|SHA1
argument_list|(
literal|"sha1"
argument_list|)
block|,
name|PROJECT
argument_list|(
literal|"project"
argument_list|)
block|,
name|FILE_LAST_MODIFIED
argument_list|(
literal|"fileLastModified"
argument_list|)
block|,
name|VERSION
argument_list|(
literal|"version"
argument_list|)
block|,
name|GROUP_ID
argument_list|(
literal|"groupId"
argument_list|)
block|,
name|ARTIFACT_ID
argument_list|(
literal|"artifactId"
argument_list|)
block|,
name|DESCRIPTION
argument_list|(
literal|"description"
argument_list|)
block|,
name|URL
argument_list|(
literal|"url"
argument_list|)
block|,
name|WHEN_GATHERED
argument_list|(
literal|"whenGathered"
argument_list|)
block|;
specifier|private
specifier|final
name|String
name|name
decl_stmt|;
specifier|private
name|ColumnNames
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|this
operator|.
name|name
operator|=
name|name
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|name
return|;
block|}
block|}
end_enum

end_unit

