begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|test
operator|.
name|parent
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_class
specifier|public
specifier|abstract
class|class
name|AbstractMergingRepositoriesTest
extends|extends
name|AbstractArchivaTest
block|{
specifier|public
name|void
name|goToAuditLogReports
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
literal|"/archiva/report/queryAuditLogReport.action"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|getRepositoryDir
parameter_list|()
block|{
name|File
name|f
init|=
operator|new
name|File
argument_list|(
literal|""
argument_list|)
decl_stmt|;
name|String
name|artifactFilePath
init|=
name|f
operator|.
name|getAbsolutePath
argument_list|()
decl_stmt|;
return|return
name|artifactFilePath
operator|+
literal|"/target/"
return|;
block|}
specifier|public
name|void
name|editManagedRepository
parameter_list|()
block|{
name|goToRepositoriesPage
argument_list|()
expr_stmt|;
name|clickLinkWithXPath
argument_list|(
literal|"//div[@id='contentArea']/div/div[5]/div[1]/a[1]/img"
argument_list|)
expr_stmt|;
name|assertPage
argument_list|(
literal|"Apache Archiva \\ Admin: Edit Managed Repository"
argument_list|)
expr_stmt|;
name|checkField
argument_list|(
literal|"repository.blockRedeployments"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Update Repository"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|getGroupId
parameter_list|()
block|{
return|return
name|getProperty
argument_list|(
literal|"VALIDARTIFACT_GROUPID"
argument_list|)
return|;
block|}
specifier|public
name|String
name|getArtifactId
parameter_list|()
block|{
return|return
name|getProperty
argument_list|(
literal|"VALIDARTIFACT_ARTIFACTID"
argument_list|)
return|;
block|}
specifier|public
name|String
name|getVersion
parameter_list|()
block|{
return|return
name|getProperty
argument_list|(
literal|"VERSION"
argument_list|)
return|;
block|}
specifier|public
name|String
name|getPackaging
parameter_list|()
block|{
return|return
name|getProperty
argument_list|(
literal|"PACKAGING"
argument_list|)
return|;
block|}
specifier|public
name|String
name|getValidArtifactFilePath
parameter_list|()
block|{
return|return
literal|"src/test/resources/snapshots/org/apache/maven/archiva/web/test/foo-bar/1.0-SNAPSHOT/foo-bar-1.0-SNAPSHOT.jar"
return|;
block|}
block|}
end_class

end_unit

