begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|test
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|test
operator|.
name|parent
operator|.
name|AbstractArchivaTest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|testng
operator|.
name|annotations
operator|.
name|Test
import|;
end_import

begin_comment
comment|/**  * Test all actions affected with CSRF security issue.  */
end_comment

begin_class
annotation|@
name|Test
argument_list|(
name|groups
operator|=
block|{
literal|"csrf"
block|}
argument_list|,
name|dependsOnMethods
operator|=
block|{
literal|"testWithCorrectUsernamePassword"
block|}
argument_list|,
name|sequential
operator|=
literal|true
argument_list|)
specifier|public
class|class
name|CSRFSecurityTest
extends|extends
name|AbstractArchivaTest
block|{
specifier|public
name|void
name|testCSRFDeleteRepository
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/deleteRepository.action?repoid=test&method%3AdeleteContents=Delete+Configuration+and+Contents"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFDeleteArtifact
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/deleteArtifact!doDelete.action?groupId=1&artifactId=1&version=1&repositoryId=snapshots"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFAddRepositoryGroup
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/addRepositoryGroup.action?repositoryGroup.id=csrfgrp"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFDeleteRepositoryGroup
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/deleteRepositoryGroup.action?repoGroupId=test&method%3Adelete=Confirm"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFDisableProxyConnector
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/disableProxyConnector!disable.action?target=maven2-repository.dev.java.net&source=internal"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFDeleteProxyConnector
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/deleteProxyConnector!delete.action?target=maven2-repository.dev.java.net&source=snapshots"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFDeleteLegacyArtifactPath
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/deleteLegacyArtifactPath.action?path=jaxen%2Fjars%2Fjaxen-1.0-FCS-full.jar"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFSaveNetworkProxy
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/saveNetworkProxy.action?mode=add&proxy.id=ntwrk&proxy.protocol=http&"
operator|+
literal|"proxy.host=test&proxy.port=8080&proxy.username=&proxy.password="
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFDeleteNetworkProxy
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/deleteNetworkProxy!delete.action?proxyid=myproxy"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFAddFileTypePattern
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/repositoryScanning!addFiletypePattern.action?pattern=**%2F*.rum&fileTypeId=artifacts"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFRemoveFileTypePattern
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/repositoryScanning!removeFiletypePattern.action?pattern=**%2F*.rum&fileTypeId=artifacts"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCSRFUpdateKnownConsumers
parameter_list|()
block|{
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
argument_list|)
expr_stmt|;
name|getSelenium
argument_list|()
operator|.
name|open
argument_list|(
name|baseUrl
operator|+
literal|"/admin/repositoryScanning!updateKnownConsumers.action?enabledKnownContentConsumers=auto-remove&"
operator|+
literal|"enabledKnownContentConsumers=auto-rename&enabledKnownContentConsumers=create-missing-checksums&"
operator|+
literal|"enabledKnownContentConsumers=index-content&enabledKnownContentConsumers=metadata-updater&"
operator|+
literal|"enabledKnownContentConsumers=repository-purge&enabledKnownContentConsumers=update-db-artifact&"
operator|+
literal|"enabledKnownContentConsumers=validate-checksums"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Security Alert - Invalid Token Found"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Possible CSRF attack detected! Invalid token found in the request."
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

