begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|web
operator|.
name|action
operator|.
name|admin
operator|.
name|connectors
operator|.
name|proxy
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|com
operator|.
name|opensymphony
operator|.
name|xwork2
operator|.
name|Preparable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|configuration
operator|.
name|AbstractRepositoryConfiguration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|configuration
operator|.
name|Configuration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|configuration
operator|.
name|ProxyConnectorConfiguration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|context
operator|.
name|annotation
operator|.
name|Scope
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|stereotype
operator|.
name|Controller
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_comment
comment|/**  * ProxyConnectorsAction  *  * @version $Id$  *   * plexus.component role="com.opensymphony.xwork2.Action" role-hint="proxyConnectorsAction" instantiation-strategy="per-lookup"  */
end_comment

begin_class
annotation|@
name|Controller
argument_list|(
literal|"proxyConnectorsAction"
argument_list|)
annotation|@
name|Scope
argument_list|(
literal|"prototype"
argument_list|)
specifier|public
class|class
name|ProxyConnectorsAction
extends|extends
name|AbstractProxyConnectorAction
implements|implements
name|Preparable
block|{
specifier|private
name|Map
argument_list|<
name|String
argument_list|,
name|AbstractRepositoryConfiguration
argument_list|>
name|repoMap
decl_stmt|;
comment|/**      * boolean to indicate that remote repo is present. Used for Add Link      */
specifier|private
name|boolean
name|remoteRepoExists
init|=
literal|false
decl_stmt|;
comment|/**      * Map of Proxy Connectors.      */
specifier|private
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|ProxyConnectorConfiguration
argument_list|>
argument_list|>
name|proxyConnectorMap
decl_stmt|;
specifier|public
name|void
name|prepare
parameter_list|()
block|{
name|Configuration
name|config
init|=
name|archivaConfiguration
operator|.
name|getConfiguration
argument_list|()
decl_stmt|;
name|repoMap
operator|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|AbstractRepositoryConfiguration
argument_list|>
argument_list|()
expr_stmt|;
name|repoMap
operator|.
name|putAll
argument_list|(
name|config
operator|.
name|getRemoteRepositoriesAsMap
argument_list|()
argument_list|)
expr_stmt|;
name|repoMap
operator|.
name|putAll
argument_list|(
name|config
operator|.
name|getManagedRepositoriesAsMap
argument_list|()
argument_list|)
expr_stmt|;
name|proxyConnectorMap
operator|=
name|createProxyConnectorMap
argument_list|()
expr_stmt|;
name|remoteRepoExists
operator|=
name|config
operator|.
name|getRemoteRepositories
argument_list|()
operator|.
name|size
argument_list|()
operator|>
literal|0
expr_stmt|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|AbstractRepositoryConfiguration
argument_list|>
name|getRepoMap
parameter_list|()
block|{
return|return
name|repoMap
return|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|ProxyConnectorConfiguration
argument_list|>
argument_list|>
name|getProxyConnectorMap
parameter_list|()
block|{
return|return
name|proxyConnectorMap
return|;
block|}
specifier|public
name|boolean
name|getRemoteRepoExists
parameter_list|()
block|{
return|return
name|remoteRepoExists
return|;
block|}
block|}
end_class

end_unit

