begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|web
operator|.
name|servlet
operator|.
name|repository
package|;
end_package

begin_comment
comment|/*  * Copyright 2001-2006 The Apache Software Foundation.  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|configuration
operator|.
name|RepositoryConfiguration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|codehaus
operator|.
name|plexus
operator|.
name|logging
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|it
operator|.
name|could
operator|.
name|webdav
operator|.
name|DAVListener
import|;
end_import

begin_import
import|import
name|it
operator|.
name|could
operator|.
name|webdav
operator|.
name|DAVProcessor
import|;
end_import

begin_import
import|import
name|it
operator|.
name|could
operator|.
name|webdav
operator|.
name|DAVRepository
import|;
end_import

begin_import
import|import
name|it
operator|.
name|could
operator|.
name|webdav
operator|.
name|DAVResource
import|;
end_import

begin_comment
comment|/**  * RepositoryMapping   *  * @author<a href="mailto:joakim@erdfelt.com">Joakim Erdfelt</a>  * @version $Id$  */
end_comment

begin_class
specifier|public
class|class
name|RepositoryMapping
implements|implements
name|DAVListener
block|{
specifier|private
name|RepositoryConfiguration
name|repositoryConfiguration
decl_stmt|;
specifier|private
name|DAVProcessor
name|davProcessor
decl_stmt|;
specifier|private
name|DAVRepository
name|davRepository
decl_stmt|;
specifier|private
name|Logger
name|logger
decl_stmt|;
specifier|public
name|RepositoryMapping
parameter_list|(
name|RepositoryConfiguration
name|repoConfig
parameter_list|)
throws|throws
name|IOException
block|{
name|this
operator|.
name|repositoryConfiguration
operator|=
name|repoConfig
expr_stmt|;
name|File
name|repoDir
init|=
operator|new
name|File
argument_list|(
name|repositoryConfiguration
operator|.
name|getDirectory
argument_list|()
argument_list|)
decl_stmt|;
name|this
operator|.
name|davRepository
operator|=
operator|new
name|DAVRepository
argument_list|(
name|repoDir
argument_list|)
expr_stmt|;
name|this
operator|.
name|davProcessor
operator|=
operator|new
name|DAVProcessor
argument_list|(
name|this
operator|.
name|davRepository
argument_list|)
expr_stmt|;
name|this
operator|.
name|davRepository
operator|.
name|addListener
argument_list|(
name|this
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DAVProcessor
name|getDavProcessor
parameter_list|()
block|{
return|return
name|davProcessor
return|;
block|}
comment|/**      *<p>Receive notification of an event occurred in a specific      * {@link DAVRepository}.</p>      */
specifier|public
name|void
name|notify
parameter_list|(
name|DAVResource
name|resource
parameter_list|,
name|int
name|event
parameter_list|)
block|{
name|String
name|message
init|=
literal|"Unknown event"
decl_stmt|;
switch|switch
condition|(
name|event
condition|)
block|{
case|case
name|DAVListener
operator|.
name|COLLECTION_CREATED
case|:
name|message
operator|=
literal|"Collection created"
expr_stmt|;
break|break;
case|case
name|DAVListener
operator|.
name|COLLECTION_REMOVED
case|:
name|message
operator|=
literal|"Collection removed"
expr_stmt|;
break|break;
case|case
name|DAVListener
operator|.
name|RESOURCE_CREATED
case|:
name|message
operator|=
literal|"Resource created"
expr_stmt|;
break|break;
case|case
name|DAVListener
operator|.
name|RESOURCE_REMOVED
case|:
name|message
operator|=
literal|"Resource removed"
expr_stmt|;
break|break;
case|case
name|DAVListener
operator|.
name|RESOURCE_MODIFIED
case|:
name|message
operator|=
literal|"Resource modified"
expr_stmt|;
break|break;
block|}
name|logger
operator|.
name|info
argument_list|(
name|message
operator|+
literal|": "
operator|+
name|this
operator|.
name|repositoryConfiguration
operator|.
name|getId
argument_list|()
operator|+
literal|" : \""
operator|+
name|resource
operator|.
name|getRelativePath
argument_list|()
operator|+
literal|"\""
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

