begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|reporting
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Date
import|;
end_import

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_comment
comment|/**  * RepositoryStatistics  *  * @author<a href="mailto:oching@apache.org">Maria Odea Ching</a>  */
end_comment

begin_class
specifier|public
class|class
name|RepositoryStatistics
block|{
specifier|private
name|String
name|repositoryId
decl_stmt|;
specifier|private
name|long
name|fileCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|totalSize
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|projectCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|groupCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|artifactCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|pluginCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|archetypeCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|jarCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|warCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|earCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|dllCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|exeCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|pomCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|deploymentCount
init|=
literal|0
decl_stmt|;
specifier|private
name|long
name|downloadCount
init|=
literal|0
decl_stmt|;
specifier|private
name|Date
name|dateOfScan
decl_stmt|;
specifier|public
name|String
name|getRepositoryId
parameter_list|()
block|{
return|return
name|repositoryId
return|;
block|}
specifier|public
name|void
name|setRepositoryId
parameter_list|(
name|String
name|repositoryId
parameter_list|)
block|{
name|this
operator|.
name|repositoryId
operator|=
name|repositoryId
expr_stmt|;
block|}
specifier|public
name|long
name|getFileCount
parameter_list|()
block|{
return|return
name|fileCount
return|;
block|}
specifier|public
name|void
name|setFileCount
parameter_list|(
name|long
name|fileCount
parameter_list|)
block|{
name|this
operator|.
name|fileCount
operator|=
name|fileCount
expr_stmt|;
block|}
specifier|public
name|long
name|getTotalSize
parameter_list|()
block|{
return|return
name|totalSize
return|;
block|}
specifier|public
name|void
name|setTotalSize
parameter_list|(
name|long
name|totalSize
parameter_list|)
block|{
name|this
operator|.
name|totalSize
operator|=
name|totalSize
expr_stmt|;
block|}
specifier|public
name|long
name|getProjectCount
parameter_list|()
block|{
return|return
name|projectCount
return|;
block|}
specifier|public
name|void
name|setProjectCount
parameter_list|(
name|long
name|projectCount
parameter_list|)
block|{
name|this
operator|.
name|projectCount
operator|=
name|projectCount
expr_stmt|;
block|}
specifier|public
name|long
name|getGroupCount
parameter_list|()
block|{
return|return
name|groupCount
return|;
block|}
specifier|public
name|void
name|setGroupCount
parameter_list|(
name|long
name|groupCount
parameter_list|)
block|{
name|this
operator|.
name|groupCount
operator|=
name|groupCount
expr_stmt|;
block|}
specifier|public
name|long
name|getArtifactCount
parameter_list|()
block|{
return|return
name|artifactCount
return|;
block|}
specifier|public
name|void
name|setArtifactCount
parameter_list|(
name|long
name|artifactCount
parameter_list|)
block|{
name|this
operator|.
name|artifactCount
operator|=
name|artifactCount
expr_stmt|;
block|}
specifier|public
name|long
name|getPluginCount
parameter_list|()
block|{
return|return
name|pluginCount
return|;
block|}
specifier|public
name|void
name|setPluginCount
parameter_list|(
name|long
name|pluginCount
parameter_list|)
block|{
name|this
operator|.
name|pluginCount
operator|=
name|pluginCount
expr_stmt|;
block|}
specifier|public
name|long
name|getArchetypeCount
parameter_list|()
block|{
return|return
name|archetypeCount
return|;
block|}
specifier|public
name|void
name|setArchetypeCount
parameter_list|(
name|long
name|archetypeCount
parameter_list|)
block|{
name|this
operator|.
name|archetypeCount
operator|=
name|archetypeCount
expr_stmt|;
block|}
specifier|public
name|long
name|getJarCount
parameter_list|()
block|{
return|return
name|jarCount
return|;
block|}
specifier|public
name|void
name|setJarCount
parameter_list|(
name|long
name|jarCount
parameter_list|)
block|{
name|this
operator|.
name|jarCount
operator|=
name|jarCount
expr_stmt|;
block|}
specifier|public
name|long
name|getWarCount
parameter_list|()
block|{
return|return
name|warCount
return|;
block|}
specifier|public
name|void
name|setWarCount
parameter_list|(
name|long
name|warCount
parameter_list|)
block|{
name|this
operator|.
name|warCount
operator|=
name|warCount
expr_stmt|;
block|}
specifier|public
name|long
name|getEarCount
parameter_list|()
block|{
return|return
name|earCount
return|;
block|}
specifier|public
name|void
name|setEarCount
parameter_list|(
name|long
name|earCount
parameter_list|)
block|{
name|this
operator|.
name|earCount
operator|=
name|earCount
expr_stmt|;
block|}
specifier|public
name|long
name|getDllCount
parameter_list|()
block|{
return|return
name|dllCount
return|;
block|}
specifier|public
name|void
name|setDllCount
parameter_list|(
name|long
name|dllCount
parameter_list|)
block|{
name|this
operator|.
name|dllCount
operator|=
name|dllCount
expr_stmt|;
block|}
specifier|public
name|long
name|getExeCount
parameter_list|()
block|{
return|return
name|exeCount
return|;
block|}
specifier|public
name|void
name|setExeCount
parameter_list|(
name|long
name|exeCount
parameter_list|)
block|{
name|this
operator|.
name|exeCount
operator|=
name|exeCount
expr_stmt|;
block|}
specifier|public
name|long
name|getPomCount
parameter_list|()
block|{
return|return
name|pomCount
return|;
block|}
specifier|public
name|void
name|setPomCount
parameter_list|(
name|long
name|pomCount
parameter_list|)
block|{
name|this
operator|.
name|pomCount
operator|=
name|pomCount
expr_stmt|;
block|}
specifier|public
name|long
name|getDeploymentCount
parameter_list|()
block|{
return|return
name|deploymentCount
return|;
block|}
specifier|public
name|void
name|setDeploymentCount
parameter_list|(
name|long
name|deploymentCount
parameter_list|)
block|{
name|this
operator|.
name|deploymentCount
operator|=
name|deploymentCount
expr_stmt|;
block|}
specifier|public
name|long
name|getDownloadCount
parameter_list|()
block|{
return|return
name|downloadCount
return|;
block|}
specifier|public
name|void
name|setDownloadCount
parameter_list|(
name|long
name|downloadCount
parameter_list|)
block|{
name|this
operator|.
name|downloadCount
operator|=
name|downloadCount
expr_stmt|;
block|}
specifier|public
name|Date
name|getDateOfScan
parameter_list|()
block|{
return|return
name|dateOfScan
return|;
block|}
specifier|public
name|void
name|setDateOfScan
parameter_list|(
name|Date
name|dateOfScan
parameter_list|)
block|{
name|this
operator|.
name|dateOfScan
operator|=
name|dateOfScan
expr_stmt|;
block|}
block|}
end_class

end_unit

