begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|admin
operator|.
name|repository
operator|.
name|managed
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|lang
operator|.
name|StringUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|inject
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_comment
comment|/**  * @author Olivier Lamy  */
end_comment

begin_class
specifier|public
class|class
name|ManagedRepositoryAdminTest
extends|extends
name|AbstractRepositoryAdminTest
block|{
annotation|@
name|Inject
specifier|private
name|ManagedRepositoryAdmin
name|managedRepositoryAdmin
decl_stmt|;
annotation|@
name|Test
specifier|public
name|void
name|getAllManagedRepos
parameter_list|()
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|ManagedRepository
argument_list|>
name|repos
init|=
name|managedRepositoryAdmin
operator|.
name|getManagedRepositories
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|repos
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|repos
operator|.
name|size
argument_list|()
operator|>
literal|0
argument_list|)
expr_stmt|;
name|log
operator|.
name|info
argument_list|(
literal|"repos "
operator|+
name|repos
argument_list|)
expr_stmt|;
comment|// check default internal
name|ManagedRepository
name|internal
init|=
name|findManagedRepoById
argument_list|(
name|repos
argument_list|,
literal|"internal"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|internal
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|internal
operator|.
name|isReleases
argument_list|()
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|internal
operator|.
name|isSnapshots
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|getById
parameter_list|()
throws|throws
name|Exception
block|{
name|ManagedRepository
name|repo
init|=
name|managedRepositoryAdmin
operator|.
name|getManagedRepository
argument_list|(
literal|"internal"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|repo
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|addDeleteManagedRepo
parameter_list|()
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|ManagedRepository
argument_list|>
name|repos
init|=
name|managedRepositoryAdmin
operator|.
name|getManagedRepositories
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|repos
argument_list|)
expr_stmt|;
name|int
name|initialSize
init|=
name|repos
operator|.
name|size
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|initialSize
operator|>
literal|0
argument_list|)
expr_stmt|;
name|ManagedRepository
name|repo
init|=
operator|new
name|ManagedRepository
argument_list|()
decl_stmt|;
name|repo
operator|.
name|setId
argument_list|(
literal|"test-new-one"
argument_list|)
expr_stmt|;
name|repo
operator|.
name|setName
argument_list|(
literal|"test repo"
argument_list|)
expr_stmt|;
name|repo
operator|.
name|setLocation
argument_list|(
name|APPSERVER_BASE_PATH
operator|+
name|repo
operator|.
name|getId
argument_list|()
argument_list|)
expr_stmt|;
name|managedRepositoryAdmin
operator|.
name|addManagedRepository
argument_list|(
name|repo
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|repos
operator|=
name|managedRepositoryAdmin
operator|.
name|getManagedRepositories
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|repos
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|initialSize
operator|+
literal|1
argument_list|,
name|repos
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|managedRepositoryAdmin
operator|.
name|getManagedRepository
argument_list|(
literal|"test-new-one"
argument_list|)
argument_list|)
expr_stmt|;
name|managedRepositoryAdmin
operator|.
name|deleteManagedRepository
argument_list|(
literal|"test-new-one"
argument_list|)
expr_stmt|;
name|repos
operator|=
name|managedRepositoryAdmin
operator|.
name|getManagedRepositories
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|repos
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|initialSize
argument_list|,
name|repos
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|private
name|ManagedRepository
name|findManagedRepoById
parameter_list|(
name|List
argument_list|<
name|ManagedRepository
argument_list|>
name|repos
parameter_list|,
name|String
name|id
parameter_list|)
block|{
for|for
control|(
name|ManagedRepository
name|repo
range|:
name|repos
control|)
block|{
if|if
condition|(
name|StringUtils
operator|.
name|equals
argument_list|(
name|id
argument_list|,
name|repo
operator|.
name|getId
argument_list|()
argument_list|)
condition|)
block|{
return|return
name|repo
return|;
block|}
block|}
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

