begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|xmlrpc
operator|.
name|services
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Date
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|util
operator|.
name|SearchUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|xmlrpc
operator|.
name|api
operator|.
name|SearchService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|xmlrpc
operator|.
name|api
operator|.
name|beans
operator|.
name|Artifact
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|archiva
operator|.
name|web
operator|.
name|xmlrpc
operator|.
name|security
operator|.
name|XmlRpcUserRepositories
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|ArchivaDAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|ArtifactDAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|browsing
operator|.
name|BrowsingResults
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|browsing
operator|.
name|RepositoryBrowsing
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|constraints
operator|.
name|ArtifactsByChecksumConstraint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|search
operator|.
name|CrossRepositorySearch
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|search
operator|.
name|SearchResultHit
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|search
operator|.
name|SearchResultLimits
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|indexer
operator|.
name|search
operator|.
name|SearchResults
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|model
operator|.
name|ArchivaArtifact
import|;
end_import

begin_comment
comment|/**  * SearchServiceImpl  *   * @version $Id: SearchServiceImpl.java  */
end_comment

begin_class
specifier|public
class|class
name|SearchServiceImpl
implements|implements
name|SearchService
block|{
specifier|private
name|CrossRepositorySearch
name|crossRepoSearch
decl_stmt|;
specifier|private
name|XmlRpcUserRepositories
name|xmlRpcUserRepositories
decl_stmt|;
specifier|private
name|ArchivaDAO
name|archivaDAO
decl_stmt|;
specifier|private
name|RepositoryBrowsing
name|repoBrowsing
decl_stmt|;
specifier|public
name|SearchServiceImpl
parameter_list|(
name|XmlRpcUserRepositories
name|xmlRpcUserRepositories
parameter_list|,
name|CrossRepositorySearch
name|crossRepoSearch
parameter_list|,
name|ArchivaDAO
name|archivaDAO
parameter_list|,
name|RepositoryBrowsing
name|repoBrowsing
parameter_list|)
block|{
name|this
operator|.
name|xmlRpcUserRepositories
operator|=
name|xmlRpcUserRepositories
expr_stmt|;
name|this
operator|.
name|crossRepoSearch
operator|=
name|crossRepoSearch
expr_stmt|;
name|this
operator|.
name|archivaDAO
operator|=
name|archivaDAO
expr_stmt|;
name|this
operator|.
name|repoBrowsing
operator|=
name|repoBrowsing
expr_stmt|;
block|}
comment|/*      * quick/general text search which returns a list of artifacts      * query for an artifact based on a checksum      * query for all available versions of an artifact, sorted in version significance order      * query for all available versions of an artifact since a given date      * query for an artifact's direct dependencies      * query for an artifact's dependency tree (as with mvn dependency:tree - no duplicates should be included)      * query for all artifacts that depend on a given artifact      */
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|quickSearch
parameter_list|(
name|String
name|queryString
parameter_list|)
throws|throws
name|Exception
block|{
comment|// 1. check whether bytecode search or ordinary search
comment|// 2. get observable repos
comment|// 3. convert results to a list of Artifact objects
name|List
argument_list|<
name|Artifact
argument_list|>
name|artifacts
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
name|List
argument_list|<
name|String
argument_list|>
name|observableRepos
init|=
name|xmlRpcUserRepositories
operator|.
name|getObservableRepositories
argument_list|()
decl_stmt|;
name|SearchResultLimits
name|limits
init|=
operator|new
name|SearchResultLimits
argument_list|(
name|SearchResultLimits
operator|.
name|ALL_PAGES
argument_list|)
decl_stmt|;
name|SearchResults
name|results
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|SearchUtil
operator|.
name|isBytecodeSearch
argument_list|(
name|queryString
argument_list|)
condition|)
block|{
name|results
operator|=
name|crossRepoSearch
operator|.
name|searchForBytecode
argument_list|(
literal|""
argument_list|,
name|observableRepos
argument_list|,
name|SearchUtil
operator|.
name|removeBytecodeKeyword
argument_list|(
name|queryString
argument_list|)
argument_list|,
name|limits
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|results
operator|=
name|crossRepoSearch
operator|.
name|searchForTerm
argument_list|(
literal|""
argument_list|,
name|observableRepos
argument_list|,
name|queryString
argument_list|,
name|limits
argument_list|)
expr_stmt|;
block|}
name|List
argument_list|<
name|SearchResultHit
argument_list|>
name|hits
init|=
name|results
operator|.
name|getHits
argument_list|()
decl_stmt|;
for|for
control|(
name|SearchResultHit
name|hit
range|:
name|hits
control|)
block|{
name|ArtifactDAO
name|artifactDAO
init|=
name|archivaDAO
operator|.
name|getArtifactDAO
argument_list|()
decl_stmt|;
name|ArchivaArtifact
name|pomArtifact
init|=
name|artifactDAO
operator|.
name|getArtifact
argument_list|(
name|hit
operator|.
name|getGroupId
argument_list|()
argument_list|,
name|hit
operator|.
name|getArtifactId
argument_list|()
argument_list|,
name|hit
operator|.
name|getVersion
argument_list|()
argument_list|,
literal|""
argument_list|,
literal|"pom"
argument_list|)
decl_stmt|;
if|if
condition|(
name|pomArtifact
operator|!=
literal|null
condition|)
block|{
name|Artifact
name|artifact
init|=
operator|new
name|Artifact
argument_list|(
name|pomArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getRepositoryId
argument_list|()
argument_list|,
name|pomArtifact
operator|.
name|getGroupId
argument_list|()
argument_list|,
name|pomArtifact
operator|.
name|getArtifactId
argument_list|()
argument_list|,
name|pomArtifact
operator|.
name|getVersion
argument_list|()
argument_list|,
name|pomArtifact
operator|.
name|getType
argument_list|()
argument_list|,
name|pomArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getWhenGathered
argument_list|()
argument_list|)
decl_stmt|;
name|artifacts
operator|.
name|add
argument_list|(
name|artifact
argument_list|)
expr_stmt|;
block|}
else|else
block|{
continue|continue;
block|}
block|}
return|return
name|artifacts
return|;
block|}
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|getArtifactByChecksum
parameter_list|(
name|String
name|checksum
parameter_list|)
throws|throws
name|Exception
block|{
comment|// 1. get ArtifactDAO from ArchivaDAO
comment|// 2. create ArtifactsByChecksumConstraint( "queryTerm" )
comment|// 3. query artifacts using constraint
comment|// 4. convert results to list of Artifact objects
name|List
argument_list|<
name|Artifact
argument_list|>
name|results
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
name|ArtifactDAO
name|artifactDAO
init|=
name|archivaDAO
operator|.
name|getArtifactDAO
argument_list|()
decl_stmt|;
name|ArtifactsByChecksumConstraint
name|constraint
init|=
operator|new
name|ArtifactsByChecksumConstraint
argument_list|(
name|checksum
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|ArchivaArtifact
argument_list|>
name|artifacts
init|=
name|artifactDAO
operator|.
name|queryArtifacts
argument_list|(
name|constraint
argument_list|)
decl_stmt|;
for|for
control|(
name|ArchivaArtifact
name|archivaArtifact
range|:
name|artifacts
control|)
block|{
name|Artifact
name|artifact
init|=
operator|new
name|Artifact
argument_list|(
name|archivaArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getRepositoryId
argument_list|()
argument_list|,
name|archivaArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getGroupId
argument_list|()
argument_list|,
name|archivaArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getArtifactId
argument_list|()
argument_list|,
name|archivaArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getVersion
argument_list|()
argument_list|,
name|archivaArtifact
operator|.
name|getType
argument_list|()
argument_list|,
name|archivaArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getWhenGathered
argument_list|()
argument_list|)
decl_stmt|;
name|results
operator|.
name|add
argument_list|(
name|artifact
argument_list|)
expr_stmt|;
block|}
return|return
name|results
return|;
block|}
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|getArtifactVersions
parameter_list|(
name|String
name|groupId
parameter_list|,
name|String
name|artifactId
parameter_list|)
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|Artifact
argument_list|>
name|artifacts
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
name|List
argument_list|<
name|String
argument_list|>
name|observableRepos
init|=
name|xmlRpcUserRepositories
operator|.
name|getObservableRepositories
argument_list|()
decl_stmt|;
name|BrowsingResults
name|results
init|=
name|repoBrowsing
operator|.
name|selectArtifactId
argument_list|(
literal|""
argument_list|,
name|observableRepos
argument_list|,
name|groupId
argument_list|,
name|artifactId
argument_list|)
decl_stmt|;
name|ArtifactDAO
name|artifactDAO
init|=
name|archivaDAO
operator|.
name|getArtifactDAO
argument_list|()
decl_stmt|;
for|for
control|(
name|String
name|version
range|:
name|results
operator|.
name|getVersions
argument_list|()
control|)
block|{
name|ArchivaArtifact
name|pomArtifact
init|=
name|artifactDAO
operator|.
name|getArtifact
argument_list|(
name|groupId
argument_list|,
name|artifactId
argument_list|,
name|version
argument_list|,
literal|""
argument_list|,
literal|"pom"
argument_list|)
decl_stmt|;
name|Artifact
name|artifact
init|=
operator|new
name|Artifact
argument_list|(
literal|""
argument_list|,
name|groupId
argument_list|,
name|artifactId
argument_list|,
name|version
argument_list|,
name|pomArtifact
operator|.
name|getType
argument_list|()
argument_list|,
name|pomArtifact
operator|.
name|getModel
argument_list|()
operator|.
name|getWhenGathered
argument_list|()
argument_list|)
decl_stmt|;
name|artifacts
operator|.
name|add
argument_list|(
name|artifact
argument_list|)
expr_stmt|;
block|}
comment|// 1. get observable repositories
comment|// 2. use RepositoryBrowsing method to query uniqueVersions?
return|return
name|artifacts
return|;
block|}
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|getArtifactVersionsByDate
parameter_list|(
name|String
name|groupId
parameter_list|,
name|String
name|artifactId
parameter_list|,
name|String
name|version
parameter_list|,
name|Date
name|since
parameter_list|)
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|Artifact
argument_list|>
name|artifacts
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
comment|// 1. get observable repositories
comment|// 2. use RepositoryBrowsing method to query uniqueVersions? (but with date)
return|return
name|artifacts
return|;
block|}
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|getDirectDependencies
parameter_list|(
name|String
name|repositoryId
parameter_list|,
name|String
name|groupId
parameter_list|,
name|String
name|artifactId
parameter_list|,
name|String
name|version
parameter_list|)
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|Artifact
argument_list|>
name|artifacts
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
return|return
name|artifacts
return|;
block|}
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|getDependencyTree
parameter_list|(
name|String
name|groupId
parameter_list|,
name|String
name|artifactId
parameter_list|,
name|String
name|version
parameter_list|)
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|Artifact
argument_list|>
name|a
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
return|return
name|a
return|;
block|}
comment|//get artifacts that depend on a given artifact
specifier|public
name|List
argument_list|<
name|Artifact
argument_list|>
name|getDependees
parameter_list|(
name|String
name|groupId
parameter_list|,
name|String
name|artifactId
parameter_list|,
name|String
name|version
parameter_list|)
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|Artifact
argument_list|>
name|artifacts
init|=
operator|new
name|ArrayList
argument_list|<
name|Artifact
argument_list|>
argument_list|()
decl_stmt|;
comment|// repo browsing usedBy?
return|return
name|artifacts
return|;
block|}
block|}
end_class

end_unit

