begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|constraints
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|lang
operator|.
name|StringUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|database
operator|.
name|Constraint
import|;
end_import

begin_comment
comment|/**  * Constraint for retrieving artifacts whose sha1 or md5 checksum matches the  * specified value.  *  */
end_comment

begin_class
specifier|public
class|class
name|ArtifactsByChecksumConstraint
extends|extends
name|AbstractDeclarativeConstraint
implements|implements
name|Constraint
block|{
specifier|private
name|String
name|whereClause
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|SHA1
init|=
literal|"SHA1"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|MD5
init|=
literal|"MD5"
decl_stmt|;
comment|/**      * Create constraint for checksum (without providing type)      *      * @param desiredChecksum the checksum (either SHA1 or MD5)      */
specifier|public
name|ArtifactsByChecksumConstraint
parameter_list|(
name|String
name|desiredChecksum
parameter_list|)
block|{
name|this
argument_list|(
name|desiredChecksum
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
comment|/**      * Create constraint for specific checksum.      *      * @param desiredChecksum the checksum (either SHA1 or MD5)      * @param type            the type of checksum (either {@link #SHA1} or {@link #MD5})      */
specifier|public
name|ArtifactsByChecksumConstraint
parameter_list|(
name|String
name|desiredChecksum
parameter_list|,
name|String
name|type
parameter_list|)
block|{
if|if
condition|(
name|StringUtils
operator|.
name|isEmpty
argument_list|(
name|type
argument_list|)
condition|)
block|{
comment|// default for no specified type.
name|whereClause
operator|=
literal|"this.checksumSHA1 == desiredChecksum || this.checksumMD5 == desiredChecksum"
expr_stmt|;
block|}
if|else if
condition|(
operator|!
name|type
operator|.
name|equals
argument_list|(
name|SHA1
argument_list|)
operator|&&
operator|!
name|type
operator|.
name|equals
argument_list|(
name|MD5
argument_list|)
condition|)
block|{
comment|// default for type that isn't recognized.
name|whereClause
operator|=
literal|"this.checksumSHA1 == desiredChecksum || this.checksumMD5 == desiredChecksum"
expr_stmt|;
block|}
if|else if
condition|(
name|type
operator|.
name|equals
argument_list|(
name|SHA1
argument_list|)
operator|||
name|type
operator|.
name|equals
argument_list|(
name|MD5
argument_list|)
condition|)
block|{
comment|// specific type.
name|whereClause
operator|=
literal|"this.checksum"
operator|+
name|type
operator|.
name|trim
argument_list|()
operator|+
literal|" == desiredChecksum"
expr_stmt|;
block|}
name|declParams
operator|=
operator|new
name|String
index|[]
block|{
literal|"String desiredChecksum"
block|}
expr_stmt|;
name|params
operator|=
operator|new
name|Object
index|[]
block|{
name|desiredChecksum
operator|.
name|toLowerCase
argument_list|()
block|}
expr_stmt|;
block|}
specifier|public
name|String
name|getSortColumn
parameter_list|()
block|{
return|return
literal|"groupId"
return|;
block|}
specifier|public
name|String
name|getWhereCondition
parameter_list|()
block|{
return|return
name|whereClause
return|;
block|}
block|}
end_class

end_unit

