begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|web
operator|.
name|test
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_comment
comment|/**  * Test archiva 'Settings'  *  */
end_comment

begin_class
specifier|public
class|class
name|SettingsTest
extends|extends
name|AbstractArchivaTestCase
block|{
comment|/*     public void testRunIndexer()     {         clickSettings();          clickLinkWithText( "Run Now" );         waitPage();          assertPage( "Administration" );          logout();     } */
specifier|public
name|void
name|testEditIndexDirectory
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"indexPath"
argument_list|,
name|getBasedir
argument_list|()
operator|+
literal|"/target/web-ui-index"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
name|getBasedir
argument_list|()
operator|+
literal|"/target/web-ui-index"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testValidIndexSchedule
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"second"
argument_list|,
literal|"*"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"minute"
argument_list|,
literal|"*"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testInvalidIndexSchedule
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"second"
argument_list|,
literal|"asdf"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Configuration"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Invalid Cron Expression"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testEditProxyHost
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.host"
argument_list|,
literal|"asdf"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testValidProxyPort
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.port"
argument_list|,
literal|"32143"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testInvalidProxyPort
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.port"
argument_list|,
literal|"asdf"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Configuration"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Port"
argument_list|)
expr_stmt|;
name|assertTextPresent
argument_list|(
literal|"Invalid field value for field \"proxy.port\""
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.port"
argument_list|,
literal|"-1"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testEditProxyCredentials
parameter_list|()
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.username"
argument_list|,
literal|"asdf"
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
block|}
comment|/**      * Click Edit Configuration link      */
specifier|private
name|void
name|clickEditConfiguration
parameter_list|()
block|{
name|clickSettings
argument_list|()
expr_stmt|;
name|clickLinkWithText
argument_list|(
literal|"Edit Configuration"
argument_list|)
expr_stmt|;
name|assertPage
argument_list|(
literal|"Configuration"
argument_list|)
expr_stmt|;
block|}
comment|/**      * Click Settings from the navigation menu      */
specifier|private
name|void
name|clickSettings
parameter_list|()
block|{
name|goToLoginPage
argument_list|()
expr_stmt|;
name|submitLoginPage
argument_list|(
name|adminUsername
argument_list|,
name|adminPassword
argument_list|)
expr_stmt|;
name|clickLinkWithText
argument_list|(
literal|"Settings"
argument_list|)
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|clickEditConfiguration
argument_list|()
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"indexPath"
argument_list|,
name|getBasedir
argument_list|()
operator|+
literal|"/target/web-ui-index"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"second"
argument_list|,
literal|"0"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"minute"
argument_list|,
literal|"0,30"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"hour"
argument_list|,
literal|"*"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"dayOfMonth"
argument_list|,
literal|"*"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"month"
argument_list|,
literal|"*"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"dayOfWeek"
argument_list|,
literal|"?"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"year"
argument_list|,
literal|""
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.port"
argument_list|,
literal|"8080"
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.host"
argument_list|,
literal|""
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.username"
argument_list|,
literal|""
argument_list|)
expr_stmt|;
name|setFieldValue
argument_list|(
literal|"proxy.password"
argument_list|,
literal|""
argument_list|)
expr_stmt|;
name|clickButtonWithValue
argument_list|(
literal|"Save Configuration"
argument_list|)
expr_stmt|;
name|waitPage
argument_list|()
expr_stmt|;
name|assertPage
argument_list|(
literal|"Administration"
argument_list|)
expr_stmt|;
name|logout
argument_list|()
expr_stmt|;
name|super
operator|.
name|tearDown
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

