begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|web
operator|.
name|action
operator|.
name|admin
operator|.
name|connectors
operator|.
name|proxy
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|lang
operator|.
name|StringUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|maven
operator|.
name|archiva
operator|.
name|configuration
operator|.
name|ProxyConnectorConfiguration
import|;
end_import

begin_comment
comment|/**  * AddProxyConnectorAction   *  * @author<a href="mailto:joakim@erdfelt.com">Joakim Erdfelt</a>  * @version $Id$  *   * @plexus.component role="com.opensymphony.xwork.Action" role-hint="addProxyConnectorAction"  */
end_comment

begin_class
specifier|public
class|class
name|AddProxyConnectorAction
extends|extends
name|AbstractProxyConnectorFormAction
block|{
annotation|@
name|Override
specifier|public
name|void
name|prepare
parameter_list|()
block|{
name|super
operator|.
name|prepare
argument_list|()
expr_stmt|;
name|connector
operator|=
operator|new
name|ProxyConnectorConfiguration
argument_list|()
expr_stmt|;
block|}
specifier|public
name|String
name|input
parameter_list|()
block|{
return|return
name|INPUT
return|;
block|}
specifier|public
name|String
name|commit
parameter_list|()
block|{
comment|/* Too complex for webwork's ${Action}-validation.xml techniques.          * Not appropriate for use with webwork's implements Validatable, as that validates regardless of          * the request method, such as .addProperty() or .addWhiteList().          *           * This validation is ultimately only useful on this one request method.          */
name|String
name|sourceId
init|=
name|connector
operator|.
name|getSourceRepoId
argument_list|()
decl_stmt|;
name|String
name|targetId
init|=
name|connector
operator|.
name|getTargetRepoId
argument_list|()
decl_stmt|;
name|ProxyConnectorConfiguration
name|otherConnector
init|=
name|findProxyConnector
argument_list|(
name|sourceId
argument_list|,
name|targetId
argument_list|)
decl_stmt|;
if|if
condition|(
name|otherConnector
operator|!=
literal|null
condition|)
block|{
name|addActionError
argument_list|(
literal|"Unable to add proxy connector, as one already exists with source repository id ["
operator|+
name|sourceId
operator|+
literal|"] and target repository id ["
operator|+
name|targetId
operator|+
literal|"]."
argument_list|)
expr_stmt|;
block|}
name|validateConnector
argument_list|()
expr_stmt|;
if|if
condition|(
name|hasActionErrors
argument_list|()
condition|)
block|{
return|return
name|INPUT
return|;
block|}
if|if
condition|(
name|StringUtils
operator|.
name|equals
argument_list|(
name|DIRECT_CONNECTION
argument_list|,
name|connector
operator|.
name|getProxyId
argument_list|()
argument_list|)
condition|)
block|{
name|connector
operator|.
name|setProxyId
argument_list|(
literal|null
argument_list|)
expr_stmt|;
block|}
name|addProxyConnector
argument_list|(
name|connector
argument_list|)
expr_stmt|;
return|return
name|saveConfiguration
argument_list|()
return|;
block|}
block|}
end_class

end_unit

